### ISSUE TITLE
data如何导入图数据库

### ISSUE THREAD

**Issue by zhangwanyu2020** [pengyou200902/Doctor-Friende#18]
你好，在你的create_graph文件中，disease-5000-end.json导入数据库报错了，请问这个文件需要导入吗？

**Comment by pengyou200902** [comment]
需要导入的整合在medical.json里了，类似disease-5000-end.json这样的文件是爬虫分块爬取时产生的。

**Comment by zhangwanyu2020** [comment]
好的，thanks
