### ISSUE TITLE
训练模型时候  path too long for Windows

### ISSUE THREAD

**Issue by pengrui-China** [pengyou200902/Doctor-Friende#38]
您好，模型训练的时候报了value Error ：stat: path too long for Windows。不知道如何处理。
![image](https://user-images.githubusercontent.com/66809352/113680577-953db280-96f3-11eb-97cb-7a7e5f58571b.png)

**Comment by pengyou200902** [comment]
1.搜索一下如何解除windows path length的限制
2.缩短你的path
