### ISSUE TITLE
前端对话窗口显示“等待服务器”

### ISSUE THREAD

**Issue by 13181268367** [pengyou200902/Doctor-Friende#39]
请问下载的CHATHTML文件放到哪里呢？我的前端打开后对话窗口那里一直显示等待服务器，也不能输入文字。谢谢

**Comment by pengyou200902** [comment]
不用和Doctor-Friende放一起，分开即可，随后[按照ReadMe](https://github.com/pengyou200902/Doctor-Friende#%E6%9C%8D%E5%8A%A1%E5%BD%A2%E5%BC%8F%E8%BF%90%E8%A1%8Cbot)所述启动服务，并且把前端的html文件serve到比如Tomcat、或者比如vscode里的live server，就可以运行/调试了

**Comment by 13181268367** [comment]
非常感谢您的回答。我按照您说的做了，结果还是有一些问题，具体如图片所示，您知道是怎么回事吗？

**Comment by pengyou200902** [comment]
没有看到图片

**Comment by 13181268367** [comment]
朋友，您好：
&nbsp; &nbsp; &nbsp; 非常感谢您的来信，github上我不太会上传图片，所以，我把我的问题和疑惑整理了一下做成了文档，在附件中。非常感谢您的帮助，对我真的很重要。如果方便的话，能不能加一下QQ（1931907246）或者微信（13181268367）。万分感激！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;我的名字：芮闯






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengyou200902/Doctor-Friende"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengyou200902/Doctor-Friende] 前端对话窗口显示“等待服务器” (#39)





 
没有看到图片
