### ISSUE TITLE
您好，在尝试数据导入neo4j时，爆出如下错误，还请指教

### ISSUE THREAD

**Issue by holdrain** [pengyou200902/Doctor-Friende#52]

**Comment by holdrain** [comment]
![image](https://user-images.githubusercontent.com/61930562/148627891-ab1acf4f-34f4-471c-99f6-d059003126d4.png)

**Comment by pengyou200902** [comment]
尝试降级neo4j的driver到3.5.x版本，或者按照最新版本的语法去修改代码
