### ISSUE TITLE
ERROR: No matching distribution found for setuptools==50.3.0.post20201006

### ISSUE THREAD

**Issue by Chenxa0** [pengyou200902/Doctor-Friende#61]
ERROR: No matching distribution found for setuptools==50.3.0.post20201006

我在执行    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt 这个命令时报这个错 
该如何解决呢？

**Comment by pengyou200902** [comment]
尝试单独安装这个依赖，比如`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple setuptools==某某版本号`，也可以不指定版本号。这个办法无法确保不会影响到其他依赖，但是可以一试。
